The contents of the updated ".github/workflows/main.yml" file will depend on the specific issue identified in the error logs. Without the error logs, I cannot provide the exact changes to be made.

However, a typical GitHub Actions workflow file for a Python project may include the following steps:

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install

      - name: Run tests
        run: make test

      - name: Code formatting
        run: make formatting

      - name: Code linting
        run: make lint

This is a basic example of a workflow file that sets up the environment, installs dependencies, runs tests, and performs code formatting and linting. The specific commands and configurations may vary depending on the project requirements.

Commit message: "feat/fix: Update GitHub Actions workflow file to fix failing run"
